"""add_multi_tenant_support

Revision ID: 30ad0a2c60b0
Revises: c8d4b0a0d1e1
Create Date: 2026-04-27 09:00:27.776711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '30ad0a2c60b0'
down_revision: Union[str, Sequence[str], None] = 'c8d4b0a0d1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_blogs', sa.Integer(), nullable=False),
    sa.Column('active_blogs', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_analytics_date'), 'platform_analytics', ['date'], unique=False)
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_slug'), 'blog', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_subdomain'), 'blog', ['subdomain'], unique=True)
    op.create_table('blog_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'AUTHOR', 'CONTRIBUTOR', name='blogrole'), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'TEAM', name='subscriptionplan'), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_ends_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id')
    )
    op.add_column('post', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_post_slug'), table_name='post')
    op.create_index(op.f('ix_post_slug'), 'post', ['slug'], unique=False)
    op.create_foreign_key(None, 'post', 'blog', ['blog_id'], ['id'])
    op.add_column('site_settings', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_site_settings_setting_key'), table_name='site_settings')
    op.create_index(op.f('ix_site_settings_setting_key'), 'site_settings', ['setting_key'], unique=False)
    op.create_foreign_key(None, 'site_settings', 'blog', ['blog_id'], ['id'])
    op.add_column('tag', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_foreign_key(None, 'tag', 'blog', ['blog_id'], ['id'])
    
    platformrole_enum = postgresql.ENUM('SUPER_ADMIN', 'USER', name='platformrole', create_type=False)
    platformrole_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('user', sa.Column('platform_role', platformrole_enum, server_default='USER', nullable=False))
    op.add_column('user', sa.Column('is_super_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='userrole'), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'is_super_admin')
    op.drop_column('user', 'platform_role')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.drop_column('tag', 'blog_id')
    op.drop_constraint(None, 'site_settings', type_='foreignkey')
    op.drop_index(op.f('ix_site_settings_setting_key'), table_name='site_settings')
    op.create_index(op.f('ix_site_settings_setting_key'), 'site_settings', ['setting_key'], unique=True)
    op.drop_column('site_settings', 'blog_id')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_post_slug'), table_name='post')
    op.create_index(op.f('ix_post_slug'), 'post', ['slug'], unique=True)
    op.drop_column('post', 'blog_id')
    op.drop_table('blog_subscriptions')
    op.drop_table('blog_members')
    op.drop_index(op.f('ix_blog_subdomain'), table_name='blog')
    op.drop_index(op.f('ix_blog_slug'), table_name='blog')
    op.drop_table('blog')
    op.drop_index(op.f('ix_platform_analytics_date'), table_name='platform_analytics')
    op.drop_table('platform_analytics')
    # ### end Alembic commands ###
