"""add_email_to_blog_invitations

Revision ID: 502b6a4898a8
Revises: 3bb1d4ac7e4a
Create Date: 2026-08-02 21:22:13.174449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '502b6a4898a8'
down_revision: Union[str, Sequence[str], None] = '3bb1d4ac7e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'blog_invitations',
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )

    conn = op.get_bind()

    conn.execute(
        sa.text(
            """
            UPDATE blog_invitations
            SET email = "user".email
            FROM "user"
            WHERE blog_invitations.accepted_by = "user".id
              AND blog_invitations.email IS NULL
            """
        )
    )

    conn.execute(sa.text("DELETE FROM blog_invitations WHERE email IS NULL"))

    op.alter_column('blog_invitations', 'email', nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blog_invitations_email'), 'blog_invitations', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_invitations_email'), table_name='blog_invitations')
    op.drop_column('blog_invitations', 'email')
    # ### end Alembic commands ###