"""add_post_status_and_published_at

Revision ID: 9d0992361088
Revises: d4e8f1a2b3c4
Create Date: 2026-06-03 22:21:46.580586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0992361088'
down_revision: Union[str, Sequence[str], None] = 'd4e8f1a2b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_blog_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_actor_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'user', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('blog_owner_id_fkey'), 'blog', type_='foreignkey')
    op.create_foreign_key(None, 'blog', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('blog_invitations_created_by_fkey'), 'blog_invitations', type_='foreignkey')
    op.drop_constraint(op.f('blog_invitations_blog_id_fkey'), 'blog_invitations', type_='foreignkey')
    op.drop_constraint(op.f('blog_invitations_accepted_by_fkey'), 'blog_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'blog_invitations', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_invitations', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_invitations', 'user', ['accepted_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('blog_members_user_id_fkey'), 'blog_members', type_='foreignkey')
    op.drop_constraint(op.f('blog_members_blog_id_fkey'), 'blog_members', type_='foreignkey')
    op.create_foreign_key(None, 'blog_members', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_members', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comment_parent_id_fkey'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('comment_user_id_fkey'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('comment_post_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('moderation_actions_actor_user_id_fkey'), 'moderation_actions', type_='foreignkey')
    op.drop_constraint(op.f('moderation_actions_moderation_item_id_fkey'), 'moderation_actions', type_='foreignkey')
    op.create_foreign_key(None, 'moderation_actions', 'moderation_items', ['moderation_item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_moderation_items_reported_by_id'), table_name='moderation_items')
    op.drop_index(op.f('ix_moderation_items_resolved_by_id'), table_name='moderation_items')
    op.drop_constraint(op.f('moderation_items_resolved_by_id_fkey'), 'moderation_items', type_='foreignkey')
    op.drop_constraint(op.f('moderation_items_blog_id_fkey'), 'moderation_items', type_='foreignkey')
    op.drop_constraint(op.f('moderation_items_reported_by_id_fkey'), 'moderation_items', type_='foreignkey')
    op.create_foreign_key(None, 'moderation_items', 'user', ['resolved_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'moderation_items', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'moderation_items', 'user', ['reported_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('post', sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', name='poststatus'), nullable=False))
    op.add_column('post', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.alter_column('post', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_post_published_at'), 'post', ['published_at'], unique=False)
    op.drop_constraint(op.f('post_author_id_fkey'), 'post', type_='foreignkey')
    op.drop_constraint(op.f('post_blog_id_fkey'), 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('site_settings', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('site_settings_blog_id_fkey'), 'site_settings', type_='foreignkey')
    op.create_foreign_key(None, 'site_settings', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tag', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'site_settings', type_='foreignkey')
    op.create_foreign_key(op.f('site_settings_blog_id_fkey'), 'site_settings', 'blog', ['blog_id'], ['id'])
    op.alter_column('site_settings', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(op.f('post_blog_id_fkey'), 'post', 'blog', ['blog_id'], ['id'])
    op.create_foreign_key(op.f('post_author_id_fkey'), 'post', 'user', ['author_id'], ['id'])
    op.drop_index(op.f('ix_post_published_at'), table_name='post')
    op.alter_column('post', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('post', 'published_at')
    op.drop_column('post', 'status')
    op.drop_constraint(None, 'moderation_items', type_='foreignkey')
    op.drop_constraint(None, 'moderation_items', type_='foreignkey')
    op.drop_constraint(None, 'moderation_items', type_='foreignkey')
    op.create_foreign_key(op.f('moderation_items_reported_by_id_fkey'), 'moderation_items', 'user', ['reported_by_id'], ['id'])
    op.create_foreign_key(op.f('moderation_items_blog_id_fkey'), 'moderation_items', 'blog', ['blog_id'], ['id'])
    op.create_foreign_key(op.f('moderation_items_resolved_by_id_fkey'), 'moderation_items', 'user', ['resolved_by_id'], ['id'])
    op.create_index(op.f('ix_moderation_items_resolved_by_id'), 'moderation_items', ['resolved_by_id'], unique=False)
    op.create_index(op.f('ix_moderation_items_reported_by_id'), 'moderation_items', ['reported_by_id'], unique=False)
    op.drop_constraint(None, 'moderation_actions', type_='foreignkey')
    op.create_foreign_key(op.f('moderation_actions_moderation_item_id_fkey'), 'moderation_actions', 'moderation_items', ['moderation_item_id'], ['id'])
    op.create_foreign_key(op.f('moderation_actions_actor_user_id_fkey'), 'moderation_actions', 'user', ['actor_user_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_post_id_fkey'), 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(op.f('comment_user_id_fkey'), 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('comment_parent_id_fkey'), 'comment', 'comment', ['parent_id'], ['id'])
    op.drop_constraint(None, 'blog_members', type_='foreignkey')
    op.drop_constraint(None, 'blog_members', type_='foreignkey')
    op.create_foreign_key(op.f('blog_members_blog_id_fkey'), 'blog_members', 'blog', ['blog_id'], ['id'])
    op.create_foreign_key(op.f('blog_members_user_id_fkey'), 'blog_members', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'blog_invitations', type_='foreignkey')
    op.drop_constraint(None, 'blog_invitations', type_='foreignkey')
    op.drop_constraint(None, 'blog_invitations', type_='foreignkey')
    op.create_foreign_key(op.f('blog_invitations_accepted_by_fkey'), 'blog_invitations', 'user', ['accepted_by'], ['id'])
    op.create_foreign_key(op.f('blog_invitations_blog_id_fkey'), 'blog_invitations', 'blog', ['blog_id'], ['id'])
    op.create_foreign_key(op.f('blog_invitations_created_by_fkey'), 'blog_invitations', 'user', ['created_by'], ['id'])
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.create_foreign_key(op.f('blog_owner_id_fkey'), 'blog', 'user', ['owner_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_actor_user_id_fkey'), 'audit_logs', 'user', ['actor_user_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_blog_id_fkey'), 'audit_logs', 'blog', ['blog_id'], ['id'])
    # ### end Alembic commands ###
