"""add ondelete=CASCADE to foreign key in blog_subscriptions table

Revision ID: caa5f4731231
Revises: ba9a10a2f3e9
Create Date: 2026-06-16 11:24:02.039704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa5f4731231'
down_revision: Union[str, Sequence[str], None] = 'ba9a10a2f3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blog_subscriptions_blog_id_fkey'), 'blog_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'blog_subscriptions', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('blog_subscriptions_blog_id_fkey'), 'blog_subscriptions', 'blog', ['blog_id'], ['id'])
    # ### end Alembic commands ###
